### ISSUE TITLE
Make L&F Jars optional

### ISSUE THREAD

**Issue by phweda** [phweda/MFM#13]
With introduction of Gradle Swing Look & Feel jars were introduced as a build dependency. These jars are optional and not required.

Re-configure Gradle to provide them as an optional feature? ( FYI phweda is total newbie to Gradle)

EaSynthLookAndFeel.jar
LiquidLnF.jar
quaqua.jar
synthetica.jar

**Comment by phweda** [comment]
Or do we just need to remove them? On startup MFM looks for those jars in MFMroot/Jars.

**Comment by voji** [comment]
Hello, 
The look and feel jars are in the "jar" directory. Current gradle build doesn't use this directory during build process, and idea project based on gradle definition (if you imported a project from gradle). 

You can see the actual dependencies (copied into fat jar) with gradle dependencies task (in idea: gradle window -> task -> help -> dependencies).

Now I working with new SettingsPanel (to improve setup user expreience for new users). If you would like, I can create a custom gradle task after that, to hadle release related task (copy the required resources to release directory)

**Comment by phweda** [comment]
Ok will defer to you on Gradle. Do what you think is best.

FYI on the current Master when I run Gradle: Tasks -> build -> jar I get those look and feel classes in the jar. Maybe a problem with my pulling it into Idea.

Yes a new SettingsPanel will be good.

**Comment by voji** [comment]
The MFM jar containing the following jars:
jmf-2.1.1e.jar
seaglasslookandfeel-0.2.jar
annotations-16.0.3.jar
jackson-core-2.9.8.jar
jackson-databind-2.9.8.jar
JTattoo-1.6.10.jar
looks-2.2.2.jar
swingx-action-1.6.5-1.jar
swingx-autocomplete-1.6.5-1.jar
swingx-common-1.6.5-1.jar
swingx-core-1.6.5-1.jar
swingx-graphics-1.6.5-1.jar
swingx-painters-1.6.5-1.jar
swingx-plaf-1.6.5-1.jar
jgoodies-common-1.7.0.jar
jackson-annotations-2.9.0.jar

If you want to create a release build, i recommend use the Task - Build - Clean and Task - Build - build commands. The result jar is there: MFM\build\libs\MFM-0.9.6.jar

**Comment by voji** [comment]
The fat jar still looks OK.
