### ISSUE TITLE
Cant find mfm.jar?

### ISSUE THREAD

**Issue by ReecaRanse** [phweda/MFM#14]
Dunno if I'm being a bit thick but once I run that bat file on windows it says:

Error: Unable to access jarfile .\MFM.jar

And I cant see mfm.jar anywhere in the download zip?

**Comment by phweda** [comment]
Did you download MFM.0.9.500.zip from [releases](https://github.com/phweda/MFM/releases/tag/0.9.5)? Unzip the root folder MFM 0.9.500 and the MFM.jar is in that folder.
