### ISSUE TITLE
Version number query

### ISSUE THREAD

**Issue by slithery** [phweda/MFM#5]
I understand that you are about to update the version number from 0.9 to 0.91
I've always been led to believe that 0.91 is 82 versions later than 0.9 (ie 0.9 then 0.10 then 0.11 etc).
Should this instead be 0.9.1 ?

Another thing you could consider would be to align the version numbers with MAME releases, that way it's obvious which is the most recent version of MAME that's known to be fully compatible. You could use point releases for any code updates which weren't relevant to MAME parsing - for example 0.188.1 0.190.1 0.190.2

**Comment by phweda** [comment]
Not sure where you got that must've been a typo on my part. This release will be 0.9.1.
No binding to MAME version would imply it is not compatible as each new version is released which is not the common case.

**Comment by hassanalasmari** [comment]
Hassanalasmari

**Comment by hassanalasmari** [comment]
https://www.youtube.com/channel/UCakrUS80_5nkda6fAQ-tahQ
